### ISSUE TITLE
MatrixCore

### ISSUE THREAD

**Issue by ghost** [MatrixCore/sdp-prac-1-roog#1]
Hey Matthew

Sorry for an off-topic issue, please feel free to delete this if undesired. I was just wondering if you're still active on GitHub and if not, if you would be interested in releasing the @MatrixCore username for use elsewhere? A couple of us are looking to set up an open source project and would love to be able to use this as the organisation name if you don't have a use for it.

Otherwise, thanks very much for reading this 🙂

**Comment by TheLastOfCakes** [comment]
Good day,

You are more than welcome to the handle, it was primarily used for study
anyway. I will delete my current GitHub account now.

Warm regards

**Comment by ghost** [comment]
You sir, are amazing! Thank you so much 🙏

Ps renaming the account would be enough to free it up, please don't feel the need to completely wipe it 🙂

**Comment by TheLastOfCakes** [comment]
Okay, great, thanks for the tip.

Just out of curiosity, what kind of project are you working on?

Matthew

**Comment by ghost** [comment]
We're looking to make a SDK written in Swift for matrix.org as the official one doesn't lend itself to being used as Swift package :(

**Comment by TheLastOfCakes** [comment]
Best of luck!

**Comment by ghost** [comment]
Thanks 😁
